#
# Provisioning status/states
#
PROV_COMPLETE_SUCCESS = 0
PROV_UNPROVISIONED = 1
PROV_INPROGRESS_DOWNLOADING = 2
PROV_INPROGRESS_APPLYING = 3
PROV_FAILED_INVALID = -1
PROV_FAILED_CONNECT = -2
PROV_FAILED_AUTH = -3
PROV_FAILED_TIMEOUT = -4
PROV_FAILED_NOT_FOUND = -5
PROV_FAILED_BAD_CONFIG = -6
PROV_FAILED_UNKNOWN = -7

